IkinciElAracUI.UI/Controllers/IhaleController.cs
using IkinciElAracUI.UI.ApiProvider;
using IkinciElAracUI.UI.Models.Core.DTO;
using IkinciElAracUI.UI.Models.VM;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Data;
using System.Text.Json;
using System.Threading.Tasks;

namespace IkinciElAracUI.UI.Controllers
{
    
    public class IhaleController : Controller
    {
        IhaleApiProvider _ihaleApiProvider;
        public IhaleController(IhaleApiProvider ihaleApiProvider)
        {
            _ihaleApiProvider = ihaleApiProvider;
        }
        [Authorize(Roles = "Admin,Kullanici,Kurumsal")]
        public async Task<IActionResult> Index()
        {
            var userJson = HttpContext.Session.GetString("kullanici");

            var myuser = System.Text.Json.JsonSerializer.Deserialize<KullaniciDTO>(userJson);

            ViewBag.kul = myuser;

            var benimIhalelerim = await _ihaleApiProvider.Ihalelerim(myuser.KullaniciID);

            ViewBag.BenimIhalelerim = benimIhalelerim;

            return View();
        }
        public async Task<IActionResult> IhaleIndex()
        {
            var userJson = HttpContext.Session.GetString("kullanici");

            var myuser = System.Text.Json.JsonSerializer.Deserialize<KullaniciDTO>(userJson);

            ViewBag.kul = myuser;

            var ihaleler = await _ihaleApiProvider.Ihaleler(myuser.RolID);

            ViewBag.Ihaleler = ihaleler;

            return View();
        }

        [HttpPost]
        public IActionResult IndexIhaleRol(int rolID)
        {
            


            return View();
        }
        [HttpPost]
        public async Task<IActionResult> IndexIhaleDetay(int ihaleID)
        {
           
            var ihaleVM = await _ihaleApiProvider.IhaleBilgisi(ihaleID);

            TempData["araIhale"] = JsonConvert.SerializeObject(ihaleVM);
            HttpContext.Session.SetString("kaydet", System.Text.Json.JsonSerializer.Serialize(2));
            return RedirectToAction("IhaleEkle");
        }

        [HttpPost]
        public IActionResult IndexIhaleEkle()
        {
            HttpContext.Session.SetString("kaydet", System.Text.Json.JsonSerializer.Serialize(1));

            return RedirectToAction("IhaleEkle");
        }

        [HttpGet]
        public IActionResult IhaleEkle()
        {
            var userJson = HttpContext.Session.GetString("kullanici");

            var myuser = System.Text.Json.JsonSerializer.Deserialize<KullaniciDTO>(userJson);

            ViewBag.kul = myuser;

            string araIhaleJson = TempData["araIhale"] as string;

            var aJson = HttpContext.Session.GetString("kaydet");

            var a = System.Text.Json.JsonSerializer.Deserialize<int>(aJson);

            

            ViewBag.Kaydet = a;

            if (araIhaleJson == null)
            {
                IhaleDTO ihale = new IhaleDTO();

                List<IhaleAracDTO> ihaleAracVMs = new List<IhaleAracDTO>();
                ihale.IhaleAracDTOs = ihaleAracVMs;
                //todo sayfa ya hiiden olarak kullnaıcıID yi ver.
                //ihale.KullaniciID = myuser.KullaniciID;
                return View(ihale);
            }
            
            var araIhale = JsonConvert.DeserializeObject<IhaleDTO>(araIhaleJson);
            if (araIhale.IhaleAracDTOs.Count <= 0)
            {
                araIhale.KullaniciID = myuser.KullaniciID;
                List<IhaleAracDTO> ihaleAracVMs = new List<IhaleAracDTO>();

                araIhale.IhaleAracDTOs = ihaleAracVMs;
            }

            araIhale.KullaniciID=myuser.KullaniciID;

            return View(araIhale);
        }

        [HttpPost]
        public IActionResult IhaleEkle(IhaleDTO vm, string name)
        {
            var userJson = HttpContext.Session.GetString("kullanici");

            var myuser = System.Text.Json.JsonSerializer.Deserialize<KullaniciDTO>(userJson);

            vm.KullaniciID = myuser.KullaniciID;
            //var sonIhale = TempData["araIhale"] as IhaleVM;
            if (name == "Kaydet")
            {
                var a = _ihaleApiProvider.IhaleKaydet(vm);
                TempData.Remove("araArac");
            }
            else if (name == "Guncelle")
            {
                var a = _ihaleApiProvider.IhaleGuncelle(vm);
                TempData.Remove("araArac");

            }
            if (name == "Ihaleye Arac Ekle")
            {
                if (vm.IhaleAracDTOs ==null)
                {
                    List<IhaleAracDTO> ihaleAracVMs = new List<IhaleAracDTO>();

                    vm.IhaleAracDTOs = ihaleAracVMs;


                }


                TempData["araIhale"] = JsonConvert.SerializeObject(vm);

                return RedirectToAction("IhaleAracEkle");
            }


            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult IhaleAracEkle()
        {
            var userJson = HttpContext.Session.GetString("kullanici");

            var myuser = System.Text.Json.JsonSerializer.Deserialize<KullaniciDTO>(userJson);

            ViewBag.kul = myuser;


            return View();
        }
        [HttpPost]
        public async Task<IActionResult> IhaleAracEkle(IhaleAracDTO vm)
        {

            string ihaleJson = TempData["araIhale"].ToString();
            var ihale = JsonConvert.DeserializeObject<IhaleDTO>(ihaleJson);


            var arac = await _ihaleApiProvider.AracBilgi(vm.AracID);
            if (arac != null)
            {
                vm.AracMarkaID = arac.AracID;
                vm.AracMarkaAdi = arac.AracMarkaAdi;
                vm.AracModelID = arac.AracModelID;
                vm.AracModelAdi = arac.AracModelAdi;
                vm.KaydedenKullanici = arac.KaydedenKullanici;
                vm.KurumsalMi = arac.KurumsalMi;
                vm.KaydedilmeZamanı = arac.KaydedilmeZamanı;

                ihale.IhaleAracDTOs.Add(vm);
            }
            

            TempData["araIhale"] = JsonConvert.SerializeObject(ihale);



            return RedirectToAction("IhaleEkle");
        }

        [HttpPost]
        public async Task<IActionResult> IndexIhaleIcerik(int ihaleID)
        {

            var ihaleVM = await _ihaleApiProvider.IhaleBilgisi(ihaleID);

            TempData["araIhale"] = JsonConvert.SerializeObject(ihaleVM);
            return RedirectToAction("IhaleIcerik");
        }
        [HttpGet]
        public IActionResult IhaleIcerik()
        {
            var userJson = HttpContext.Session.GetString("kullanici");

            var myuser = System.Text.Json.JsonSerializer.Deserialize<KullaniciDTO>(userJson);

            ViewBag.kul = myuser;

            string araIhaleJson = TempData["araIhale"] as string;
            var araIhale = JsonConvert.DeserializeObject<IhaleDTO>(araIhaleJson);

            
            return View(araIhale);
        }
        [HttpPost]
        public IActionResult IndexAracTeklif(int ihaleAracID)
        {
            HttpContext.Session.SetString("ihaleAracID", System.Text.Json.JsonSerializer.Serialize(ihaleAracID));
            //var aracTeklif = await _ihaleApiProvider.AracTeklif(ihaleAracID);

            //TempData["araAracTeklif"] = JsonConvert.SerializeObject(aracTeklif);

            //HttpContext.Session.SetString("araAracTeklif", System.Text.Json.JsonSerializer.Serialize(aracTeklif));



            return RedirectToAction("AracTeklif");

        }
        [HttpGet]
        public async Task<IActionResult> AracTeklif()
        {
            var userJson = HttpContext.Session.GetString("kullanici");

            var myuser = System.Text.Json.JsonSerializer.Deserialize<KullaniciDTO>(userJson);

            ViewBag.kul = myuser;

            //var araAracTeklifJson = HttpContext.Session.GetString("araAracTeklif");

            //var aracTeklif = System.Text.Json.JsonSerializer.Deserialize<IhaleFiyatDTO>(araAracTeklifJson);


            //string araAracTeklifJson = TempData["araAracTeklif"] as string;
            //var aracTeklif = JsonConvert.DeserializeObject<IhaleFiyatDTO>(araAracTeklifJson);
            var ihaleAracIDJson = HttpContext.Session.GetString("ihaleAracID");

            var ihaleAracID = System.Text.Json.JsonSerializer.Deserialize<int>(ihaleAracIDJson);

            var aracTeklif = await _ihaleApiProvider.AracTeklif(ihaleAracID);

            return View(aracTeklif);

        }

        [HttpGet]
        public IActionResult IndexTeklif()
        {
            var userJson = HttpContext.Session.GetString("kullanici");

            var myuser = System.Text.Json.JsonSerializer.Deserialize<KullaniciDTO>(userJson);

            ViewBag.kul = myuser;

            

            //var aracTeklif = await _ihaleApiProvider.AracTeklif(ihaleFiyatID);


            return View();

        }
        [HttpPost]
        public async Task<IActionResult> IndexTeklif(FiyatDTO dto)
        {
            var userJson = HttpContext.Session.GetString("kullanici");

            var myuser = System.Text.Json.JsonSerializer.Deserialize<KullaniciDTO>(userJson);

            var ihaleAracIDJson = HttpContext.Session.GetString("ihaleAracID");

            var ihaleAracID = System.Text.Json.JsonSerializer.Deserialize<int>(ihaleAracIDJson);

            dto.KullaniciID = myuser.KullaniciID;
            dto.IhaleAracID= ihaleAracID;

            var aracTeklif = await _ihaleApiProvider.TeklifKaydet(dto);


            return RedirectToAction("AracTeklif");

        }
    }
}

IkinciElAracUI.UI/Views/Ihale/AracTeklif.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model IhaleFiyatDTO
<h2>İhale Arac Teklif</h2>



<div class="row" style="margin-top: 20px;">
    @Html.HiddenFor(a => a.IhaleFiyatID)
    @Html.HiddenFor(a => a.IhaleID)
</div>
<div class="row" style="margin-top: 20px;">
    <div class="col-md-4">
        İhale Adı:
        @Html.TextBoxFor(a => a.Plaka, new { @readonly = "readonly" })
    </div>
    <div class="col-md-4">
        İhale Adı:
        @Html.TextBoxFor(a => a.AracMarkaAdi, new { @readonly = "readonly" })
    </div>
    <div class="col-md-4">
        İhale Adı:
        @Html.TextBoxFor(a => a.AracModelAdi, new { @readonly = "readonly" })
    </div>
</div>


<div class="card mb-4">
    <div class="card-header">
        <i class="fas fa-table me-1"></i>
        Teklif Listesi
    </div>
    <div class="card-body">
        <table id="datatablesSimple">
            <thead>
                <tr>
                    <th>Kullanıcı Adı</th>
                    <th>Fiyat</th>
                </tr>
            </thead>
            <tfoot>
            </tfoot>
            <tbody>


                @for (int i = 0; i < Model.FiyatList.Count; i++)
                {
                    <tr>
                        <td>
                            @Html.TextBoxFor(a => a.FiyatList[i].KullaniciAdi, new { @readonly = "readonly" })
                        </td>
                        <td>
                            @Html.TextBoxFor(a => a.FiyatList[i].Fiyat, new { @readonly = "readonly" })
                        </td>
                        
                    </tr>
                }
            </tbody>
        </table>

        


    </div>
</div>
<div class="row" style="margin-top: 20px;">



    <div class="col-md-4">
        <form method="get" action="@Url.Action("IndexTeklif", "Ihale")">
            <button type="submit" class="btn btn-primary">Araca Teklif Ver</button>
        </form>
       
    </div>
    <div class="col-md-4">
        
        <form method="post" action="@Url.Action("IndexIhaleIcerik", "Ihale")">
            <input type="hidden" name="IhaleAracID" value="@Model.IhaleID" />
            <button type="submit" class="btn btn-primary">İhale Sayfasın Dön</button>
        </form>

    </div>

</div>

IkinciElAracUI.UI/Views/Ihale/IhaleAracEkle.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model IhaleAracVM


<h2>İhaleye Araç Ekle</h2>


@using (Html.BeginForm("IhaleAracEkle", "Ihale", FormMethod.Post))
{

    <div class="row" style="margin-top: 20px;">
            <div class="col-md-4">



            @*@for (int i = 0; i < Model.IhaleAracVMs.Count; i++)*@
            @*{*@
                
                @*@Html.DropDownListFor(model => model.IhaleAracVMs[i].AracID, new SelectList(ViewBag.AracIDlist, "AracID", "AracID"), "Seçiniz");*@


           @* }*@
           @* @Html.DropDownListFor(model => model.AracID, new SelectList(ViewBag.AracIDlist, "AracID", "AracID"), "Seçiniz")*@
            <label>AracID:</label>
            @Html.TextBoxFor(a=>a.AracID)
        </div>
    </div>
    <div class="row" style="margin-top: 20px;">
        <div class="col-md-4">
            <label>Ihale Başlangıç Fiyatı:</label>
            @Html.TextBoxFor(a=>a.IhaleBaslangicFiyati)
        </div>
    </div>
    <div class="row" style="margin-top: 20px;">
        <div class="col-md-4">
            <label>Max Alım Fiyatı:</label>
            @Html.TextBoxFor(a=>a.MaxAlimFiyati)

        </div>

            
    </div>
    <div class="col-md-4 d-flex justify-content-start">
        <input type="submit" name="name" value="Kaydet" class="btn btn-primary" />
    </div>

}

IkinciElAracUI.UI/Views/Ihale/IhaleEkle.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model IhaleDTO
<h2>İhale Ekle</h2>


    @using (Html.BeginForm("IhaleEkle", "Ihale", FormMethod.Post))
    {
        <div class="row" style="margin-top: 20px;">
            @Html.HiddenFor(a => a.IhaleID)
        </div>
        <div class="row" style="margin-top: 20px;">
            <div class="col-md-4">
                İhale Adı:
                @Html.TextBoxFor(a => a.IhaleAdi, new { @class = "form-control" })
            </div>
            <div class="col-md-4">
                BireyselMi/KurumsalMı:
                @Html.DropDownListFor(model => model.KurumsalMi, new List<SelectListItem>()
                {
                    new SelectListItem() { Text = "Bireysel", Value = "False" },
                    new SelectListItem() { Text = "Kurumsal", Value = "True" }
                }, "Seçiniz", new { @class = "form-control" })

            </div>
            @*<div class="col-md-4">
                Sirket:
                @Html.DropDownListFor(model => model.SirketID, new SelectList(ViewBag.Sirketlist, "SirketID", "SirketAdi"), "Seçiniz", new { @class = "form-control" })

            </div>*@
        </div>
        <div class="row" style="margin-top: 20px;">
            <div class="col-md-4">
                Statu:
                @Html.DropDownListFor(model => model.IhaleStatuID, new List<SelectListItem>()
                {
                    new SelectListItem() { Text = "Başlamadı", Value = "1" },
                    new SelectListItem() { Text = "Başladı", Value = "2" },
                    new SelectListItem() { Text = "Bittti", Value = "3" },
                    new SelectListItem() { Text = "İptal", Value = "4" }
                }, "Seçiniz", new { @class = "form-control" })

            </div>

        @*<div class="col-md-4">
            <label class="form-label">İhale Başlangıç tarihi</label>
            <input type="date" class="form-control" value="@Model.IhaleBaslangicTarihi">
        </div>

        <div class="col-md-4">
            <label class="form-label">İhale Başlangıç Saati</label>
            <input type="time" class="form-control" value="@Model.IhaleBaşlangıçSaati">
        </div>
        <div class="col-md-4">
            <label class="form-label">İhale Bitiş tarihi</label>
            <input type="date" class="form-control" value="@Model.IhaleBitistarihi">
        </div>
        <div class="col-md-4">
            <label class="form-label">İhale Bitiş Saati</label>
            <input type="time" class="form-control" value="@Model.IhaleBitisSaati">
        </div>*@
            @*<div class="col-md-4">
                Statu:
            @Html.DropDownListFor(model => model.IhaleStatuID, new SelectList(ViewBag.SatatuList, "IhaleStatuID", "IhaleStatuAdi"), "Seçiniz", new { @class = "form-control" })

            </div>*@
            @*<div class="col-md-4"> başlangıç ve bitişi datatime tipinde al
                Model:
                @Html.DropDownListFor(model => model.AracModelID, new SelectList(ViewBag.ModelList, "AracModelID", "AracModelAdi"), "Seçiniz", new { @class = "form-control" })
            </div>
            <div class="col-md-4">
                GovdeTipi:
                @Html.DropDownListFor(model => model.GovdeTipiID, new SelectList(ViewBag.GovdeTipilist, "GovdeTipiID", "GovdeTipiAdi"), "Seçiniz", new { @class = "form-control" })
            </div>*@
        </div>


    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Ihale Arac Listesi
        </div>
        <div class="card-body">
            <table id="datatablesSimple">
                <thead>
                    <tr>
                        <th>AracID</th>
                        <th>Arac Marka</th>
                        <th>Arac Model</th>
                        <th>Kurumsal mı</th>
                        <th>Kaydeden Kullanıcı</th>
                        <th>Kaydedilme Zamanı</th>
                    </tr>
                </thead>
                <tfoot>
                </tfoot>
                <tbody>


                    @for (int i = 0; i < Model.IhaleAracDTOs.Count; i++)
                    {
                        <tr>
                            <td>
                                @Html.TextBoxFor(a => a.IhaleAracDTOs[i].AracID, new { @readonly = "readonly" })
                            </td>
                            <td>
                                @Html.TextBoxFor(a => a.IhaleAracDTOs[i].AracMarkaAdi, new { @readonly = "readonly" })
                            </td>
                            <td>
                                @Html.TextBoxFor(a => a.IhaleAracDTOs[i].AracModelAdi, new { @readonly = "readonly" })
                            </td>
                            <td>
                                @Html.TextBoxFor(a => a.IhaleAracDTOs[i].KurumsalMi, new { @readonly = "readonly" })
                            </td>
                            <td>
                                @Html.TextBoxFor(a => a.IhaleAracDTOs[i].KaydedenKullanici, new { @readonly = "readonly" })
                            </td>
                            <td>
                                @Html.TextBoxFor(a => a.IhaleAracDTOs[i].KaydedilmeZamanı, new { @readonly = "readonly" })
                            </td>
                            <td>
                            @*<td>
                    <form method="post" action="@Url.Action("AracCikar", "Home")">
                    <input type="hidden" name="AracID" value="@item.AracID" />
                    <button type="submit" class="btn btn-danger">Arac çıkar</button>
                    </form>
                    </td>*@
                            <td>@Html.HiddenFor(a=>a.IhaleAracDTOs[i].IhaleAracID)</td>

                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>


        <div class="row" style="margin-top: 20px;">
            <div class="col-md-4">
                <input type="submit" name="name" value="Ihaleye Arac Ekle" class="btn btn-primary" />
            </div>


            @if (ViewBag.Kaydet == 1)
            {
                <div class="col-md-4 d-flex justify-content-end">
                    <input type="submit" name="name" value="Kaydet" class="btn btn-primary" />
                </div>
            }
            else
            {

                <div class="col-md-4 d-flex justify-content-end">
                    <input type="submit" name="name" value="Guncelle" class="btn btn-primary" />
                </div>
            }


        </div>





    }

IkinciElAracUI.UI/Views/Ihale/IhaleIcerik.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model IhaleDTO
<h2>İhale İçerik</h2>



    <div class="row" style="margin-top: 20px;">
        @Html.HiddenFor(a => a.IhaleID)
    </div>
    <div class="row" style="margin-top: 20px;">
        <div class="col-md-4">
            İhale Adı:
            @Html.TextBoxFor(a => a.IhaleAdi, new { @class = "form-control" })
        </div>
        <div class="col-md-4">
            BireyselMi/KurumsalMı:
            @Html.DropDownListFor(model => model.KurumsalMi, new List<SelectListItem>()
        {
        new SelectListItem() { Text = "Bireysel", Value = "False" },
        new SelectListItem() { Text = "Kurumsal", Value = "True" }
        }, "Seçiniz", new { @class = "form-control" })

        </div>
        @*<div class="col-md-4">
    Sirket:
    @Html.DropDownListFor(model => model.SirketID, new SelectList(ViewBag.Sirketlist, "SirketID", "SirketAdi"), "Seçiniz", new { @class = "form-control" })

    </div>*@
    </div>
    <div class="row" style="margin-top: 20px;">
        <div class="col-md-4">
            Statu:
            @Html.DropDownListFor(model => model.IhaleStatuID, new List<SelectListItem>()
        {
        new SelectListItem() { Text = "Başlamadı", Value = "1" },
        new SelectListItem() { Text = "Başladı", Value = "2" },
        new SelectListItem() { Text = "Bittti", Value = "3" },
        new SelectListItem() { Text = "İptal", Value = "4" }
        }, "Seçiniz", new { @class = "form-control" })

        </div>

        <div class="col-md-4">
    <label class="form-label">İhale Başlangıç tarihi</label>
    <input type="date" class="form-control" value="@Model.IhaleBaslangicTarihi">
    </div>
        <div class="col-md-4">
            <label class="form-label">İhale Bitiş tarihi</label>
            <input type="date" class="form-control" value="@Model.IhaleBitisTarihi">
        </div>
        @*
    <div class="col-md-4">
    <label class="form-label">İhale Başlangıç Saati</label>
    <input type="time" class="form-control" value="@Model.IhaleBaşlangıçSaati">
    </div>
    
    <div class="col-md-4">
    <label class="form-label">İhale Bitiş Saati</label>
    <input type="time" class="form-control" value="@Model.IhaleBitisSaati">
    </div>*@
        @*<div class="col-md-4">
    Statu:
    @Html.DropDownListFor(model => model.IhaleStatuID, new SelectList(ViewBag.SatatuList, "IhaleStatuID", "IhaleStatuAdi"), "Seçiniz", new { @class = "form-control" })

    </div>*@
        @*<div class="col-md-4"> başlangıç ve bitişi datatime tipinde al
    Model:
    @Html.DropDownListFor(model => model.AracModelID, new SelectList(ViewBag.ModelList, "AracModelID", "AracModelAdi"), "Seçiniz", new { @class = "form-control" })
    </div>
    <div class="col-md-4">
    GovdeTipi:
    @Html.DropDownListFor(model => model.GovdeTipiID, new SelectList(ViewBag.GovdeTipilist, "GovdeTipiID", "GovdeTipiAdi"), "Seçiniz", new { @class = "form-control" })
    </div>*@
    </div>


    <div class="card mb-4">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Ihale Arac Listesi
        </div>
        <div class="card-body">
            <table id="datatablesSimple">
                <thead>
                    <tr>
                        <th>AracID</th>
                        <th>Arac Marka</th>
                        <th>Arac Model</th>
                        <th>Kurumsal mı</th>
                        <th>Kaydeden Kullanıcı</th>
                        <th>Kaydedilme Zamanı</th>
                    </tr>
                </thead>
                <tfoot>
                </tfoot>
                <tbody>


                    @for (int i = 0; i < Model.IhaleAracDTOs.Count; i++)
                    {
                        <tr>
                            <td>
                                @Html.TextBoxFor(a => a.IhaleAracDTOs[i].AracID, new { @readonly = "readonly" })
                            </td>
                            <td>
                                @Html.TextBoxFor(a => a.IhaleAracDTOs[i].AracMarkaAdi, new { @readonly = "readonly" })
                            </td>
                            <td>
                                @Html.TextBoxFor(a => a.IhaleAracDTOs[i].AracModelAdi, new { @readonly = "readonly" })
                            </td>
                            <td>
                                @Html.TextBoxFor(a => a.IhaleAracDTOs[i].KurumsalMi, new { @readonly = "readonly" })
                            </td>
                            <td>
                                @Html.TextBoxFor(a => a.IhaleAracDTOs[i].KaydedenKullanici, new { @readonly = "readonly" })
                            </td>
                            <td>
                                @Html.TextBoxFor(a => a.IhaleAracDTOs[i].KaydedilmeZamanı, new { @readonly = "readonly" })
                            </td>
                            <td>
                            
                            <td>@Html.HiddenFor(a=>a.IhaleAracDTOs[i].IhaleAracID)</td>
                            <td>
                                <form method="post" action="@Url.Action("IndexAracTeklif", "Ihale")">
                                    <input type="hidden" name="IhaleAracID" value="@Model.IhaleAracDTOs[i].IhaleAracID" />
                                    <button type="submit" class="btn btn-primary">Teklif Ver</button>
                                </form>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

IkinciElAracUI.UI/Views/Ihale/IndexTeklif.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model FiyatDTO

@using (Html.BeginForm("IndexTeklif", "Ihale", FormMethod.Post))
{

    <div class="row" style="margin-top: 20px;">
        <div class="col-md-6">
            @Html.TextBoxFor(a=>a.Fiyat)
        </div>
    </div>

    <div class="row" style="margin-top: 20px;">
        <div class="col-3">
            <input type="submit" name="name" value="Teklif Kaydet" class="btn btn-primary btn-lg btn-block" />
        </div>
    </div>


                            
}