IkinciElAracUI.UI/Controllers/GirisController.cs
using IkinciElAracUI.UI.ApiProvider;
using IkinciElAracUI.UI.Models.Core.DTO;
using IkinciElAracUI.UI.Models.VM;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Text.Json;
using System.Threading.Tasks;
using System.Xml.Linq;

namespace IkinciElAracUI.UI.Controllers
{
    public class GirisController : Controller
    {

        KullaniciApiProvider _kullaniciApiProvider;
        public GirisController(KullaniciApiProvider kullaniciApiProvider)
        {
            _kullaniciApiProvider = kullaniciApiProvider;
        }
        [AllowAnonymous]
        public IActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
               

                return RedirectToAction("Index", "Ihale");

            }
            return View();
        }
        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> Index(KullaniciVM vm)
        {

                var kullnici = await _kullaniciApiProvider.Kontrol(vm);
                ClaimsIdentity identity = null;
                bool isAuthenticate = false;
                if (kullnici != null)
                {
                    

                    identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);

                    identity.AddClaim(new Claim(ClaimTypes.Role, kullnici.RolAdi));

                    identity.AddClaim(new Claim(ClaimTypes.Name, kullnici.KullaniciAdi));
                    isAuthenticate = true;


                }
                if (isAuthenticate)
                {
                    var principal = new ClaimsPrincipal(identity);
                    HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);
                    HttpContext.Session.SetString("kullanici", JsonSerializer.Serialize(kullnici));
                    return RedirectToAction("Index", "Ihale");
                    
                }

            return View();

        }

        public IActionResult Logout()
        {
            HttpContext.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

IkinciElAracUI.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewData["Title"] - IkinciElAracUI.UI</title>

    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>

    @*<link href="~/Content/bootstrap.min.css" rel="stylesheet" />*@
    @*<script src="~/Scripts/bootstrap.min.js"></script>*@
    <link href="~/css/styles.css" rel="stylesheet" />

    <link href="c:\users\mahmu\.nuget\packages\bootstrap\5.2.3\contentfiles\any\any\wwwroot\css\bootstrap.min.css" rel="stylesheet" />



    <script src="c:\users\mahmu\.nuget\packages\bootstrap\5.2.3\contentfiles\any\any\wwwroot\js\bootstrap.min.js"></script>



</head>
<body>
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="index.html">2. El Araç İhale</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
            </div>
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="#!">@ViewBag.kul.AdVeSoyad</a></li>
                    <li><a class="dropdown-item" href="#!">Activity Log</a></li>
                    <li><hr class="dropdown-divider" /></li>
                    <li>
                        <form action="@Url.Action("LogOut", "Giris")" method="post">
                            <input type="submit" value="Çıkış Yap" class="btn" />
                        </form>
                    </li>
                </ul>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Sayfalar</div>
                        <a class="nav-link" href="/Ihale/Index">

                            Benim İhalelerim
                        </a>

                        <a class="nav-link" href="/Ihale/IhaleIndex">

                            İhaleler
                        </a>



                        <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                        </div>


                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Giriş Yapan Kişi:</div>
                    @ViewBag.kul.AdVeSoyad
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                    <main role="main" class="pb-3">
                        @RenderBody()
                    </main>
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2023</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>

</body>
</html>